### ISSUE TITLE
[Wayland] [Sway] Disconnected after +-20s not on focused workspace.

### ISSUE THREAD

**Issue by ToxicMushroom** [goatcorp/wine-xiv-git#19]
I think the game stops processing events, since when I bring its workspace in focus I get a flood of messages in chat and everything teleports, OR I see that I got disconnected.

Audio keeps playing while on the unfocused workspace so it does not hang completely ?

This is not an issue on the non wayland bunlded xivlauncher wine I used before.

System:
```
Kernel: 6.7.1-arch1-1
WM: Sway (Wayland)
GPU: AMD Radeon RX 6650 XT
```

**Comment by rankynbass** [comment]
You should post this on my repo, not here.
https://github.com/rankynbass/unofficial-wine-xiv-git/tree/xiv-wayland

**Comment by ToxicMushroom** [comment]
> You should post this on my repo, not here. https://github.com/rankynbass/unofficial-wine-xiv-git/tree/xiv-wayland

Oh oop, I guess this one was in my search history as well an I mixed them up ;-;. Issues on your repo are currently closed though
